### ISSUE TITLE
Generated client has no server url override

### ISSUE THREAD

**Issue by ADRFranklin** [mnahkies/openapi-code-generator#266]
Hi,

Path objects allow overriding the main server url, so that specific paths may deviate from the original server url. 

```yaml
/user:
  get:
    servers:
      - url: https://plex.tv/api/v2
    tags:
      - Authentication
    summary: Get Token Details
    description: Get the User data from the provided X-Plex-Token
    operationId: getTokenDetails
    responses:
      "200":
        description: Logged in user details
        content:
          application/json:
            schema:
              $ref: ../../models/UserPlexAccount.yaml
      "400":
        $ref: "../../responses/400.yaml"
      "401":
        $ref: "../../responses/401.yaml"
```

what is generated is this
```ts
  async getTokenDetails(
    timeout?: number,
    opts: AxiosRequestConfig = {},
  ): Promise<AxiosResponse<t_getTokenDetailsJson200Response>> {
    const url = `/user`;
    const headers = this._headers({}, opts.headers);

    return this._request({
      url: url,
      method: 'GET',
      ...(timeout ? { timeout } : {}),
      ...opts,
      headers,
    });
  }
  ```
  
which I believe to be wrong, since the only way to work around it is overriding the baseUrl with opts, or override the function in another class that extends the generated client. But it would be nice to have the url override the format so it becomes instead

  ```ts
  const url = `https://plex.tv/api/v2/user`;
  ```

**Comment by mnahkies** [comment]
Yeah that's not yet supported (btw in case you haven't seen I've added a compatibility table to try and document what properties are used https://openapi-code-generator.nahkies.co.nz/overview/compatibility#operation-object), but can think about adding it.

The `servers` array in general is something that's always seemed a bit tricky to support tbh - I recently added support for optionally using the root servers object to generate string literal types as hints in https://github.com/mnahkies/openapi-code-generator/pull/246 but haven't actually started using it at runtime.

There's two main question marks in my head:
- how to choose which `servers` element to use
- how to deal with `variables`

Choosing which one explicitly by making it a type hint rather than a runtime concern seemed like a good trade-off to me, as generally speaking I'd expect things like base URLs to be sourced from your applications configuration in the 12 factor app style anyway (eg: environment variables/config files/cli args).

Since it's not uncommon to list out `dev` / `stage` hosts in definitions there's also an aspect of wanting to avoid leaking information about these into the transpiled bundles (when using it for frontend applications).

Perhaps one option could be to support `servers` at the operation level, but iff it's an array of length 1, ie: there's no ambiguity.

I guess ideally `variables` would be parsed and probably just surfaced in the same way that route placeholders are.

It would be nice if the `server` object had a `id` / `key` property that could be used to tag which related to eachother, but I don't think there's an official attribute for this (eg: tag a URL as `dev` / `prod` so that changing the root base URL would also automatically select the correct path level URLs)

Be curious if you had any thoughts on the best way to support this, and also how important/unimportant you think support for `variables` is

**Comment by mnahkies** [comment]
Still a work in progress, but working on it over in https://github.com/mnahkies/openapi-code-generator/pull/272 - will probably refine the API a bit more.

Uses branded string types, which I'm not totally sure is a good idea, but allows for supporting variable substitution which can't be done with string literal types alone

**Comment by mnahkies** [comment]
I've now merged, though not quite published those changes (want to test in a few more projects before publishing, should happen the next couple of days).

The docs are here https://openapi-code-generator.nahkies.co.nz/guides/concepts/servers-object-handling

In summary:
- routes with a `servers` override have a new position parameter defaulting to the first server URL with default values for any variables
- a new class to build URLs from declared `servers` replacing placeholder variables is exported
- there's a cli flag to turn off the URL builder and just use `string`

Hopefully this works for you, let me know if you have any feedback and thanks for raising!

**Comment by mnahkies** [comment]
Released in https://github.com/mnahkies/openapi-code-generator/releases/tag/v0.17.0
